package com.rails.entity;

import java.util.List;

import lombok.Data;

@Data
public class Hotel {
	private String hotelId;
	private String bizdate;
	private String updateTime;
	private String oldHotelId;
	private String hotelName;
	private String hotelNameEn;
	private Double basePrice;
	private String hotelGroup;
	private String companyType;
	private String fromChannel;
	private String hotelClass1;
	private String hotelClass2;
	private String hotelClass2Name;
	private String oldHotelClass;
	private String starLevel;
	private String oldStarLevel;
	private String chainBrand;
	private String chainBrandName;
	private String oldChainBrand;
	private String oldChainBrandName;
	private String isOnlineSignUp;
	private String address;
	private String tel;
	private String email;
	private String fax;
	private String linkman;
	private String linkmanPhone;
	private String linkmanOther;
	private Integer priority;
	private String location;
	private Double longitude;
	private Double latitude;
	private Integer country;
	private String countryName;
	private String oldCountry;
	private String oldCountryName;
	private Integer province;
	private String provinceName;
	private String oldProvince;
	private String oldProvinceName;
	private Integer city;
	private String cityName;
	private String oldCity;
	private String oldCityName;
	private String countyCode;
	private String countyName;
	private String oldCountyCode;
	private String oldCountyName;
	private List<Landmark> landmark;
	private List<OldLandmark> oldLandmark;
	private List<BusinessArea> businessArea;
	private List<OldBusinessArea> oldBusinessArea;
	private String announcement;
	private String introduction;
	private String setupYear;
	private String decorateYear;
	private List<HotelPolicy> hotelPolicy;
	private List<HotelFacility> hotelFacility;
	private String tags;
	private String hotelTips;
	private String supportCard;
	private String supportCurrency;
	private String foreignGuests;
	private String isSmokeless;
	private String dawnFlag;
	private String receiptFlag;
	private String examineType;
	private String hotelState;
	private String validFlag;
	private String createTime;
	private String versionNo;
	private String introductionVector;
	private Double hotelScore;
	private String latestOrderTime;
	private String belongComp1;
	private String belongComp2;
	private String nodeNum;
	private String hotelFlag1;
	private String hotelFlag2;
	private String hotelFlag3;
	private String hotelFlag4;
	private String hotelFlag5;
	private String hotelFlag6;
	private String hotelFlag7;
	private String hotelFlag8;
	private String hotelFlag9;
	private String hotelFlag10;
}